name: ci

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-24.04
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install linter
        run: |
          python -m pip install -U pip
          pip install ruff==0.5.6
      - name: Lint (optional)
        run: ruff check .